name: skargo
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - sphinx-pythia-theme
  - python=3.9
  - numpy
  - scipy

  # Data packages
  - pandas
  - xarray
  - jupyter
  - netcdf4
  - gsw
  - argopy

  # ML Packages
  - scikit-learn

  # Images
  - cmocean
  - plotly
  - matplotlib
  - seaborn 
  - haversine
  - geopandas
  - pygam
  - cartopy
  - imageio
  - rasterio
  - hyperopt
  - dataframe_image

